name: test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  formula:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tap repository
        run: brew tap jacklv-coder/tap "$GITHUB_WORKSPACE"
      - name: Install formula
        run: brew install jacklv-coder/tap/ipcheck
      - name: Test formula
        run: brew test jacklv-coder/tap/ipcheck
